version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
            RAILS_ENV: test
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    working_directory: ~/bowling

    steps:
      - checkout

      - restore_cache:
          keys:
            - bowling-{{ .Branch }}{{ checksum "Gemfile.lock" }}

      - run:
          name: install dependencies
          command: |
            bundle install --without development \
                           --deployment \
                           --jobs=3 \
                           --retry=3

      - save_cache:
          key: bowling-{{ .Branch }}{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      # Database setup
      - run: cp .env.example .env
      - run: bundle exec rake db:create

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rspec
